server:
  port: 8084
spring:
  application:
    name: datapool-datasync
  profiles:
    active: dev

#kafka个人配置
kafka:
  topic-name:
    table-sync-task: sync-table-task
    table-full-read: table-full-read
    table-after-mapping: table-after-mapping

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://10.10.1.122:3306/zkbh-test?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: bohuatech_2018
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  #Kafka
  kafka:
    bootstrap-servers: 172.16.8.240:9092
    consumer:
#      max-poll-records: 1000
      enable-auto-commit: true
      auto-offset-reset: latest
#    listener:
#      concurrency: 4

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/

elasticsearch:
  hosts: 172.16.8.240:9200

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://10.10.169.31:4000/information_schema?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=CST&useSSL=false
    username: businessuseratdbpool
    password: dbpool
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  #Kafka
  kafka:
    bootstrap-servers: 192.168.0.13:9092
    consumer:
      #      max-poll-records: 1000
      enable-auto-commit: true
      auto-offset-reset: latest
#    listener:
#      concurrency: 4

eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.32:1025/eureka/
elasticsearch:
  hosts: 192.168.0.8:9200,192.168.0.12:9200,192.168.0.5:9200,192.168.0.15:9200