server:
  port: 8084
spring:
  application:
    name: datapool-delete
  profiles:
    active: dev


mybatis:
  mapper-locations: classpath:mappers/**/*.xml
---
spring:
  profiles: dev
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 88888888
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/information_schema?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=CST&useSSL=false&useLegacyDatetimeCode=false
      username: root
      password: 88888888
      driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/
elasticsearch:
  hosts: localhost:9200
  index-prefix: jwdsj-datapool-index-
  alias-prefix: jwdsj-datapool-alias-


---
spring:
  profiles: prd
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 88888888
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://192.168.2.8:3306/information_schema?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=CST&useSSL=false&useLegacyDatetimeCode=false
      username: root
      password: 88888888
      driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/
elasticsearch:
  hosts: localhost:9200
  index-prefix: jwdsj-datapool-index-
  alias-prefix: jwdsj-datapool-alias-