server:
  port: 8081
spring:
  application:
    name: datapool-dictionary
  profiles:
    active: dev



#定义kafka的一些主题
kafka:
  topic-name:
    #    dict-column-update: dict-column-update
    #    dict-database-update: dict-database-update
    #    dict-table-update: dict-table-update
    dict-update: dict-update

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
---
spring:
  profiles: dev
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 88888888
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/information_schema?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=CST&useSSL=false&useLegacyDatetimeCode=false
      username: root
      password: 88888888
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      location: /home/centos/data/temp/datapool
  #Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: false
      auto-offset-reset: latest
      listener:
        ack-mode: manual
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/


---
spring:
  profiles: prd
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 88888888
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://192.168.2.8:3306/information_schema?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=CST&useSSL=false&useLegacyDatetimeCode=false
      username: root
      password: 88888888
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      location: /home/centos/data/temp/datapool
  #Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: false
      auto-offset-reset: latest
      listener:
        ack-mode: manual
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/
