server:
  port: 8081
spring:
  application:
    name: datapool-dictionary
  profiles:
    active: dev



#定义kafka的一些主题
kafka:
  topic-name:
#    dict-column-update: dict-column-update
#    dict-database-update: dict-database-update
#    dict-table-update: dict-table-update
    dict-update: dict-update

mybatis:
  mapper-locations: classpath:mappers/*.xml
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://10.10.1.122:3306/zkbh-test?characterEncoding=UTF-8
    username: root
    password: bohuatech_2018
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      location: C:\\Users\\wangjinhao\\AppData\\Local\\datapool
  #Kafka
  kafka:
    bootstrap-servers: 172.16.8.240:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/


---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://10.10.169.31:4000/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: businessuseratdbpool
    password: dbpool
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      location: /home/centos/data/temp/datapool
  #Kafka
  kafka:
    bootstrap-servers: 10.10.169.141:9092

eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.32:1025/eureka/