server:
  port: 8888
spring:
  application:
    name: datapool-gateway
  profiles:
    active: dev

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 1000


---
spring:
  profiles: dev
  servlet:
    multipart:
      location: C:\\Users\\wangjinhao\\AppData\\Local\\datapool
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/

---
spring:
  profiles: test
  servlet:
    multipart:
      location: /home/centos/data/temp/datapool
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.32:1025/eureka/

---
spring:
  profiles: yk
  servlet:
    multipart:
      location: C:\\Users\\dell\\AppData\\Local\\datapool
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/