server:
  port: 8888

spring:
  application:
    name: datapool-gateway
  profiles:
    active: dev

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 1000


---
spring:
  profiles: dev
  servlet:
    multipart:
      location: /home/centos/data/temp/datapool
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/

---
spring:
  profiles: prd
  servlet:
    multipart:
      location: /home/centos/data/temp/datapool
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/