server:
  port: 8082

spring:
  application:
    name: datapool-indexmanage
  profiles:
    active: dev

#定义kafka的一些主题
kafka:
  topic-name:
    #    dict-column-update: dict-column-update
    #    dict-database-update: dict-database-update
    #    dict-table-update: dict-table-update
    dict-update: dict-update
    table-sync-task: sync-table-task


---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://10.10.1.122:3306/zkbh-test?characterEncoding=UTF-8
    username: root
    password: bohuatech_2018
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  #Kafka
  kafka:
    bootstrap-servers: 172.116.8.240:9092
    consumer:
      enable-auto-commit: false
      auto-offset-reset: latest
    listener:
      ack-mode: manual
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/
elasticsearch:
  hosts: 172.16.8.240:9200
  index-prefix: jwdsj-datapool-index-
  alias-prefix: jwdsj-datapool-alias-

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://10.10.169.31:4000/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: businessuseratdbpool
    password: dbpool
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  #Kafka
  kafka:
    bootstrap-servers: 10.10.169.141:9092
    consumer:
      enable-auto-commit: false
      auto-offset-reset: latest
    listener:
      ack-mode: manual
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.32:1025/eureka/
elasticsearch:
  hosts: 10.10.169.142:9200,10.10.169.147:9200,10.10.169.164:9200,10.10.169.158:9200
  index-prefix: jwdsj-datapool-index-
  alias-prefix: jwdsj-datapool-alias-
