server:
  port: 8082

spring:
  application:
    name: datapool-indexmanage
  profiles:
    active: dev

#定义kafka的一些主题
kafka:
  topic-name:
    dict-update: dict-update
    table-full-read: table-full-read


---
spring:
  profiles: dev
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 88888888
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/information_schema?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=CST&useSSL=false&useLegacyDatetimeCode=false
      username: root
      password: 88888888
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  #Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      #      max-poll-records: 1000
      enable-auto-commit: true
      auto-offset-reset: latest
    listener:
      ack-mode: manual
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/
elasticsearch:
  hosts: localhost:9200
  index-prefix: jwdsj-datapool-index-
  alias-prefix: jwdsj-datapool-alias-

---
spring:
  profiles: prd
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 88888888
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://192.168.2.8:3306/information_schema?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=CST&useSSL=false&useLegacyDatetimeCode=false
      username: root
      password: 88888888
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  #Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      #      max-poll-records: 1000
      enable-auto-commit: true
      auto-offset-reset: latest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/
elasticsearch:
  hosts: localhost:9200
  index-prefix: jwdsj-datapool-index-
  alias-prefix: jwdsj-datapool-alias-
