spring:
  application:
    name: datapool-indexmanage
  profiles:
    active: dev

#定义kafka的一些主题
kafka:
  topic-name:
    #    dict-column-update: dict-column-update
    #    dict-database-update: dict-database-update
    #    dict-table-update: dict-table-update
    dict-update: dict-update


---
server:
  port: 8082
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://10.10.1.122:3306/zkbh-test?characterEncoding=UTF-8
    username: root
    password: bohuatech_2018
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  #Kafka
  kafka:
    bootstrap-servers: 172.16.8.240:9092
    consumer:
      enable-auto-commit: true
      auto-offset-reset: latest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/
elasticsearch:
  hosts: 172.16.8.240:9200
  index-prefix: jwdsj-datapool-index-
  alias-prefix: jwdsj-datapool-alias-