spring:
  application:
    name: datapool-indexmanage
  profiles:
    active: dev


---
server:
  port: 8082
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://10.10.1.122:3306/zkbh-test?characterEncoding=UTF-8
    username: root
    password: bohuatech_2018
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/
elasticsearch:
  hosts: 172.16.8.204:9200
  index-prefix: jwdsj-datapool-