server:
  port: 8082


spring:
  application:
    name: datapool-indexmanage
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true


#定义kafka的一些主题
kafka:
  topic-name:
    dict-update: dict-update
    table-full-read: table-full-read


---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 88888888
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  #Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      #      max-poll-records: 1000
      enable-auto-commit: true
      auto-offset-reset: latest

jwdb:
  jdbc-url: jdbc:mysql://localhost:3306/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
  username: root
  password: 88888888
  driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/
elasticsearch:
  hosts: localhost:9200
  index-prefix: jwdsj-datapool-index-
  alias-prefix: jwdsj-datapool-alias-

---
spring:
  profiles: prd
  datasource:
    url: jdbc:mysql://localhost:3306/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 88888888
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  #Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      #      max-poll-records: 1000
      enable-auto-commit: true
      auto-offset-reset: latest
jwdb:
  jdbc-url: jdbc:mysql://localhost:3306/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
  username: root
  password: 88888888
  driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/
elasticsearch:
  hosts: localhost:9200
  index-prefix: jwdsj-datapool-index-
  alias-prefix: jwdsj-datapool-alias-
