server:
  port: 8085
spring:
  application:
    name: datapool-search
  profiles:
    active: dev


---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://10.10.1.122:3306/zkbh-test?characterEncoding=UTF-8
    username: root
    password: bohuatech_2018
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  redis:
    host: 10.10.169.79
    port: 6379
    password: ict@123
    database: 3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/
elasticsearch:
  hosts: 172.16.8.240:9200
  # 表聚合的最大数目
  max-table-agg: 30
  index-prefix: jwdsj-datapool-index-
  alias-prefix: jwdsj-datapool-alias-

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://10.10.169.31:4000/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: businessuseratdbpool
    password: dbpool
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.32:1025/eureka/
elasticsearch:
  hosts: 10.10.169.142:9200,10.10.169.147:9200,10.10.169.164:9200,10.10.169.158:9200
  # 表聚合的最大数目
  max-table-agg: 30
  index-prefix: jwdsj-datapool-index-
  alias-prefix: jwdsj-datapool-alias-

---
spring:
  profiles: yk
  datasource:
    url: jdbc:mysql://localhost:3306/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/
elasticsearch:
  hosts: 192.168.110.128:9200
  # 表聚合的最大数目
  max-table-agg: 30
  index-prefix: jwdsj-datapool-index-
  alias-prefix: jwdsj-datapool-alias-