server:
  port: 8083
spring:
  application:
    name: datapool-search
  profiles:
    active: dev


---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 88888888
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/
elasticsearch:
  hosts: localhost:9200
  # 表聚合的最大数目
  max-table-agg: 30
  index-prefix: jwdsj-datapool-index-
  alias-prefix: jwdsj-datapool-alias-

---
spring:
  profiles: prd
  datasource:
    url: jdbc:mysql://localhost:3306/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 88888888
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/
elasticsearch:
  hosts: localhost:9200
  # 表聚合的最大数目
  max-table-agg: 30
  index-prefix: jwdsj-datapool-index-
  alias-prefix: jwdsj-datapool-alias-
