server:
  port: 8086
spring:
  application:
    name: datapool-data-overview
  profiles:
    active: dev


---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://10.10.1.122:3306/zkbh-test?characterEncoding=UTF-8
    username: root
    password: bohuatech_2018
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/


---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://10.10.169.31:4000/dbpool?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: businessuseratdbpool
    password: dbpool
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.32:1025/eureka/